version: '3'
services:
  misdp:
    build: .
    image: misdp
    container_name: misdp
    volumes:
      - .:/home
      - ./mosek.lic:/home/mosek/mosek.lic
      - ./gurobi.lic:/opt/gurobi/gurobi.lic:ro
    tty: true
